name: Test => Build => Deploy


on: push


jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: ITProKyle/action-setup-python@v0.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry install -vv
      - uses: pre-commit/action@v3.0.0
